#普通数据的配置
name: zhangsan

#对象的配置
person:
  name: zhangsan
  age: 18
  addr: beijing
#行内对象配置
#person: {name: zhangsan,age: 18,addr: beijing }
server:
  port: 8082
#配置数据、集合
city:
  - beijing
  - tianjing
  - chongqing
  - shanghai
#city: [beijing,tianjing,chongqing,shanghai]

#配置数据、集合（对象数据）
student:
  - name: tom
    age: 18
    addr: beijing
  - name: lucy
    age: 19
    addr: suzhou
#student: [{name: tom,age: 18, addr: beijing},{name: lucy,age: 19, addr: suzhou}]

#Map配置
map:
  key1: value1
  key2: value2